### ISSUE TITLE
RPostgreSQL breaks on r-release-osx-x86_64

### ISSUE THREAD

**Issue by edzer** [tomoakin/RPostgreSQL#87] opened 2017-06-16 12:37 UTC
Seen [here](https://cran.r-project.org/web/checks/check_results_RPostgreSQL.html): the package breaks on r-release-osx-x86_64. Is anyone looking at how to resolve that? Quite a few reverse dependencies (including dbplyr, sf and dplyr) break as well, due to this.

**Comment by tomoakin** [comment] 2017-06-26 01:25
Thank you for this notification. I replaced the libpq and compiled on Sierra. This as a new release 0.6-2 is accepted at CRAN and waiting for the process to make binary for every platforms.  Since was confirmed to build on Sierra, I hope it will get ok on the CRAN release machine setup as well.

**Comment by tomoakin** [comment] 2017-07-07 00:39
Closing as 0.6-2 got OK.

**Closed by tomoakin** 2017-07-07 00:39 UTC
